// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd11PuIzJEEpREtjSZXrvmyPss1lumGws',
    appId: '1:692678397937:web:ac8b0bee061a879497be50',
    messagingSenderId: '692678397937',
    projectId: 'semester-project-680c7',
    authDomain: 'semester-project-680c7.firebaseapp.com',
    storageBucket: 'semester-project-680c7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-S22Ym9mC7xMLgmgxTFtAPiVEI2xVSqA',
    appId: '1:692678397937:android:7b7815f467479b9c97be50',
    messagingSenderId: '692678397937',
    projectId: 'semester-project-680c7',
    storageBucket: 'semester-project-680c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMt2Kl_IVpiys961mJo-1a4P-_hvv_Cf8',
    appId: '1:692678397937:ios:eb0052f72d3298c397be50',
    messagingSenderId: '692678397937',
    projectId: 'semester-project-680c7',
    storageBucket: 'semester-project-680c7.firebasestorage.app',
    iosBundleId: 'com.example.semesterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMt2Kl_IVpiys961mJo-1a4P-_hvv_Cf8',
    appId: '1:692678397937:ios:eb0052f72d3298c397be50',
    messagingSenderId: '692678397937',
    projectId: 'semester-project-680c7',
    storageBucket: 'semester-project-680c7.firebasestorage.app',
    iosBundleId: 'com.example.semesterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd11PuIzJEEpREtjSZXrvmyPss1lumGws',
    appId: '1:692678397937:web:f204cedfcc7f490297be50',
    messagingSenderId: '692678397937',
    projectId: 'semester-project-680c7',
    authDomain: 'semester-project-680c7.firebaseapp.com',
    storageBucket: 'semester-project-680c7.firebasestorage.app',
  );
}
